### ISSUE TITLE
Don't restrict on owner being a zero value address

### ISSUE THREAD

**Issue by achiurizo** [omgnetwork/ex_plasma#30]
This is a double issue. 

First, should we restrict on the owner being a zero value? Per contract, this is [not a valid value for output_guard/owner](https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/contracts/src/transactions/FungibleTokenOutputModel.sol#L46). However, we use zero-value owner's when we produce the [TypedData signature](https://github.com/omisego/elixir-omg/blob/master/apps/omg/lib/omg/typed_data_hash.ex#L34). 

Second, when inserting Utxo structs with a zero address owner, no error is raised and we are able to produce the Transaction struct

```elixir
outputs = [
  %Utxo{amount: 1, currency: <<0::160>>, owner: <<0::160>>},
  %Utxo{amount: 2, currency: <<0::160>>, owner: <<0::160>>},
  %Utxo{amount: 3, currency: <<0::160>>, owner: <<0::160>>}
 ]

transaction = Transaction.new(%Transaction{inputs: [], outputs: outputs})
#=> should return {:error, {:owner, :cannot_be_zero}}
```

**Comment by boolafish** [comment]
> However, we use zero-value owner's when we produce the TypedData signature.

That was some restriction on the meta mask if I remember it correctly. It used to not support dynamic array. As a result, in our EIP712 struct, we always fill the array to length of 4 with empty values when it is not existing in original tx.

**Comment by pnowosie** [comment]
@boolafish @achiurizo Input / Output with all zero-values is __special case for empty__ one. Not sure about origin, but Eip-712 is not the case because it isn't working on RLP-decoded structs but on it's own structures (struct hash pads the in/outputs arrays).

Some voice in my head tells me the reason we rejected empty entities is because if we accept them and then filter them out later, it's easy to produce 2 txs that differs on txhash...

We run of at least a few of dis-ambiguity issues recently related to empty entities, so I'd recommend a caution if we want to accept them back.

**Comment by kevsul** [comment]
As @boolafish said, when we produce the TypeData signature we pad tx inputs and outputs with null values because Metamask didn't support dynamic arrays. It does now, but we ran out of time to update our implementation. Maybe in the future.

And the reason that we don't allow null inputs or outputs in the RLP encoding of a transaction is because of this - the EIP encoding can't differentiate between a null input and a non-existing input, so we could have 2 **different** transactions (e.g. one with just 1 valid input and another with 1 valid input and 1 null input) but with the **same** signature. Same goes for outputs.
This is a problem.

One example of why this is a problem:
Consider you're trying to exit an output of a transaction, T1 = [[input0],[output0]].
I can construct another transaction T2 = [[input0,nullInput][output0]] which has same signature as T1. I can now use T2 to challenge T1's exit and you lose your funds 😞

**Comment by kevsul** [comment]
Oops, didn't see your comment @pnowosie 😛 

> From the other hand nothing is wrong with owner = <<0::160>> (when the whole Output isn't empty) it's equally "bad" as owner = <random>.

Yep a zero address is technically fine, but we decided to disallow it, as we couldn’t come up with a valid use case and the opinion from a security point of view was to be more restrictive rather than less.

**Comment by pdobacz** [comment]
Also, on disallowing `<<0::160>>` and all other zero-values:

I was initially more in favor of being _permissive_ in such cases, but the thing that convinced me most, is that zero is something resembling `null` in EVM, and as such - a magic value.

So I now fully concur, that it is generally good to avoid zero-values whenever possible.

**Comment by achiurizo** [comment]
Okay thanks for the input all. How about this proposal:

* contracts maintains the same validations, no changes
* ex_plasma as a client library allows the zero value to be encoded, contracts will reject it if its in the 'wrong' place.

The reasoning for this is elixir-omg(and ex_plasma) has a few key points where the encoding is coupled to allow 0 values(see [typed_signed_validator](https://github.com/omisego/elixir-omg/blob/master/apps/omg_watcher_rpc/lib/web/validators/typed_data_signed.ex) as one example). I think this gives the library the flexibility to work around this constraint yet still providing enough enforcement to validate as much of the transaction format before sending it off to the contracts.
